import type { TourStep } from "./types";

// 39-step master script across 8 acts. Khaleeji Arabic narration.

export const tourScript: TourStep[] = [
  { id: "act1-intro", act: "Act 1 — Hook",
    narration: "السلام عليكم. أنا عبدالله، مرشدك في منصّة معهد الإدارة العامة. خلال الدقائق القادمة، راح أعرّفك على المنصّة كاملة — من التسجيل إلى المقابلة الرسمية. تقدر تقاطعني في أي وقت بالميكروفون أو بالكتابة.",
    durationEstimateMs: 16_000 },
  { id: "act1-landing", act: "Act 1 — Hook", route: "/",
    narration: "هذي الصفحة الرئيسية. المشكلة: المقابلات مرعبة، والتوظيف بطيء. نقدّم ثلاث رحلات تعليمية: تدريب، سيرة ذاتية، ومسار مؤسسي للمدرّبين.",
    spotlight: { selector: "h1", label: "نظرة عامة" }, durationEstimateMs: 12_000 },
  { id: "act1-features", act: "Act 1 — Hook", route: "/features",
    narration: "صفحة الميزات الكاملة. ستّ ركائز: التدريب الآمن، التقييم الرسمي، منشئ السيرة، محادثة بناء السيرة، تقييم السيرة، ولوحة المدرّب.",
    spotlight: { selector: "h1", label: "الميزات" }, durationEstimateMs: 13_000 },

  { id: "act2-signup-form", act: "Act 2 — Signup", route: "/login?tab=signup",
    narration: "أول خطوة لأي مستخدم: التسجيل. عادةً تكتب بريدك وكلمة سرّ. خلّيني أعبّيها كمثال — لكن مو راح أضغط زر التسجيل، عشان نكمّل بحساب تجريبي جاهز.",
    spotlight: { selector: "form", label: "نموذج التسجيل" },
    action: { kind: "type", selector: "input[type='email']", text: "demo.candidate@ipa.sa", speedMs: 40 },
    durationEstimateMs: 15_000 },
  { id: "act2-reset-password", act: "Act 2 — Signup", route: "/login?forgot=1",
    narration: "إذا نسيت كلمة المرور، تقدر تستعيدها من هنا. تكتب بريدك، يوصلك رابط، تعيّن كلمة جديدة. بسيط وآمن.",
    spotlight: { selector: "input[type='email']", label: "استعادة كلمة المرور" }, durationEstimateMs: 10_000 },
  { id: "act2-session-swap-candidate", act: "Act 2 — Signup",
    narration: "حسناً، خلّينا نتجاوز خطوة التحقّق ونكمّل وكأنّك سجّلت دخولك للتوّ. راح أحوّل الجلسة الآن إلى حساب تجريبي جاهز…",
    action: { kind: "swap-session", role: "candidate" }, durationEstimateMs: 8_000 },
  { id: "act2-complete-profile", act: "Act 2 — Signup", route: "/complete-profile",
    narration: "أول مرّة تسجّل، تشوف هذي الصفحة — إكمال الملف الشخصي. الاسم، التخصّص، سنوات الخبرة، اللغة، والمدينة. تساعد الـ AI يخصّص لك المقابلات.",
    spotlight: { selector: "h1, h2", label: "إكمال الملف" }, durationEstimateMs: 13_000 },
  { id: "act2-first-dashboard", act: "Act 2 — Signup", route: "/dashboard/candidate",
    narration: "وأخيراً، لوحتك الشخصية. هنا تشوف تقدّمك، سيرتك، آخر المقابلات، وفرص الوظائف.",
    spotlight: { selector: "h1, h2", label: "لوحة المرشّح" }, durationEstimateMs: 9_000 },

  { id: "act2.5-nav-walkthrough", act: "Act 2.5 — Navigation",
    narration: "خلّيني أعرّفك على شريط التنقّل العلوي. هنا تنتقل بين الميزات الرئيسية: لوحة التحكّم، السيرة، المقابلات، الوظائف، التوجيه المهني. وفي اليسار قائمة حسابك وتسجيل الخروج.",
    spotlight: { selector: "header, nav", label: "شريط التنقّل" }, durationEstimateMs: 14_000 },
  { id: "act2.5-language-toggle", act: "Act 2.5 — Navigation",
    narration: "ومن أهم الميزات: التبديل بين العربية والإنجليزية بضغطة واحدة. كل المنصّة ثنائية اللغة بالكامل.",
    spotlight: { selector: "[data-tour='language-toggle'], button[aria-label*='language']", label: "تبديل اللغة" }, durationEstimateMs: 11_000 },

  { id: "act3-cv-hub", act: "Act 3 — CV", route: "/cv",
    narration: "حان وقت بناء السيرة الذاتية. ثلاث طرق: منشئ يدوي بسبع خطوات، محادثة موجَّهة، أو رفع سيرة موجودة للتقييم.",
    spotlight: { selector: "main", label: "ثلاث طرق" }, durationEstimateMs: 13_000 },
  { id: "act3-cv-builder", act: "Act 3 — CV", route: "/cv/builder",
    narration: "الطريقة الأولى: المنشئ اليدوي. سبع خطوات. أهم ميزة: زر 'اقترح بـ AI' يحوّل النصّ الحرّ إلى STAR احترافي.",
    spotlight: { selector: "main", label: "منشئ السيرة" }, durationEstimateMs: 13_000 },
  { id: "act3-cv-chat", act: "Act 3 — CV", route: "/cv/interview",
    narration: "الطريقة الثانية: المحادثة. ١٥ سؤال موجَّه يبني سيرتك من الصفر. سترى سعد، شخصيّتنا التجريبية، يجاوب بصوته الخاص.",
    spotlight: { selector: "main", label: "محادثة السيرة" }, durationEstimateMs: 11_000 },
  { id: "act3-cv-review", act: "Act 3 — CV", route: "/cv/review",
    narration: "الطريقة الثالثة: تقييم سيرة موجودة. ترفع PDF، الـ AI يحلّله، يطلع رسم radar، ويعطيك تبريرات لكل ملاحظة.",
    spotlight: { selector: "main", label: "رفع وتقييم" }, durationEstimateMs: 12_000 },
  { id: "act3-career-guidance", act: "Act 3 — CV", route: "/career-guidance",
    narration: "بعد ما تكتمل سيرتك، تأتي صفحة التوجيه المهني. الـ AI يقترح مسارات وظيفية، يحلّل فجوات مهاراتك، ويعطيك موارد تعليمية.",
    spotlight: { selector: "main", label: "التوجيه المهني" }, durationEstimateMs: 12_000 },

  { id: "act4-dashboard-revisit", act: "Act 4 — Practice", route: "/dashboard/candidate",
    narration: "نرجع للوحة المرشّح. سيرة سعد الآن جاهزة، والإحصائيات بدأت تتعبّى. الخطوة التالية: التدريب.",
    spotlight: { selector: "main", label: "تقدّم المرشّح" }, durationEstimateMs: 10_000 },
  { id: "act4-practice-voice", act: "Act 4 — Practice", route: "/interview/voice?practice=true&question_count=3",
    narration: "مقابلة تدريبية. ثلاث أسئلة بصوت سعودي. الميزة الكبيرة: ما تنحفظ في ملف المرشّح ولا تظهر للـ HR. تخطئ، تتعلّم، تكرّر — بأمان.",
    spotlight: { selector: "main", label: "وضع التدريب" }, durationEstimateMs: 14_000 },
  { id: "act4-text-mode", act: "Act 4 — Practice", route: "/interview/text",
    narration: "نفس المقابلة لكن نصّياً — للحالات اللي ما يفضّل فيها المستخدم الصوت.",
    spotlight: { selector: "main", label: "وضع نصّي" }, durationEstimateMs: 8_000 },
  { id: "act4-video-mode", act: "Act 4 — Practice", route: "/interview/video",
    narration: "وهذي مقابلة الفيديو — تُستخدم في التقييم الرسمي مع Proctor للتأكّد من هوية المرشّح.",
    spotlight: { selector: "main", label: "وضع الفيديو" }, durationEstimateMs: 9_000 },
  { id: "act4-practice-results", act: "Act 4 — Practice",
    narration: "بعد كل مقابلة تدريبية، تشوف نتيجة غنيّة: تحليل DISC، تغذية STAR، إعادة كتابة محسَّنة، ورسم radar للمهارات. الهدف: تتعلّم 'لماذا' — لا فقط 'كم درجة'.",
    spotlight: { selector: "main", label: "نتائج التدريب" }, durationEstimateMs: 14_000 },

  { id: "act4.5-profile-settings", act: "Act 4.5 — Settings", route: "/settings/profile",
    narration: "إعدادات الملف الشخصي. تقدر تحدّث اسمك، صورتك، نبذة عنك، لغتك المفضّلة، وكلمة السرّ.",
    spotlight: { selector: "main", label: "إعدادات الملف" }, durationEstimateMs: 9_000 },
  { id: "act4.5-interview-settings", act: "Act 4.5 — Settings", route: "/settings/interview",
    narration: "إعدادات المقابلة: الوضع الافتراضي، اللغة، صوت المحاوِر، ومستوى الصعوبة.",
    spotlight: { selector: "main", label: "إعدادات المقابلة" }, durationEstimateMs: 8_000 },

  { id: "act5-jobs", act: "Act 5 — Assessment", route: "/jobs",
    narration: "صفحة الوظائف. هنا تتصفّح الوظائف المتاحة وتقدّم. خلّيني أختار 'مهندس واجهات أمامية' تناسب سعد.",
    spotlight: { selector: "main", label: "الوظائف" }, durationEstimateMs: 11_000 },
  { id: "act5-job-apply", act: "Act 5 — Assessment",
    narration: "نضغط 'تقديم'، يظهر نموذج وبعده زر 'ابدأ التقييم'. هذي بداية المقابلة الرسمية المُسجَّلة.",
    spotlight: { selector: "main", label: "تقديم على الوظيفة" }, durationEstimateMs: 10_000 },
  { id: "act5-assessment-run", act: "Act 5 — Assessment", route: "/interview/voice?job_id=demo&question_count=3",
    narration: "المقابلة التقييمية تختلف عن التدريبية: تتطلّب موافقة صريحة، فحص ميكروفون وكاميرا، ثم تنطلق في وضع مُسجَّل بدرجات.",
    spotlight: { selector: "main", label: "المقابلة الرسمية" }, durationEstimateMs: 12_000 },
  { id: "act5-assessment-results", act: "Act 5 — Assessment",
    narration: "نتائج المقابلة الرسمية تشبه التدريبية لكن مع تقييم مرجَّح بدرجة نهائية — تقني ٤٠٪، تواصل ٣٠٪، ملاءمة ثقافية ٣٠٪. هذي الدرجة تذهب للـ HR.",
    spotlight: { selector: "main", label: "النتيجة المرجَّحة" }, durationEstimateMs: 14_000 },

  { id: "act6-session-swap-admin", act: "Act 6 — Admin",
    narration: "حسناً، الآن لنرى ماذا يرى المسؤول (Admin) خلال هذه العملية. راح أبدّل الجلسة إلى حساب مسؤول تجريبي…",
    action: { kind: "swap-session", role: "admin" }, durationEstimateMs: 8_000 },
  { id: "act6-admin-dashboard", act: "Act 6 — Admin", route: "/dashboard/admin",
    narration: "لوحة المسؤول. قائمة المقابلات (لاحظ سعد في الأعلى لأنّه أنهى تقييمه للتوّ)، تحليلات شاملة، ورسوم مرئية.",
    spotlight: { selector: "main", label: "لوحة المسؤول" }, durationEstimateMs: 13_000 },
  { id: "act6-admin-interviews", act: "Act 6 — Admin", route: "/admin/interviews",
    narration: "إدارة المقابلات بشكل أعمق: فلترة بالحالة، البحث بالاسم، إجراءات جماعية.",
    spotlight: { selector: "main", label: "قائمة المقابلات" }, durationEstimateMs: 11_000 },
  { id: "act6-admin-settings", act: "Act 6 — Admin", route: "/admin/settings",
    narration: "أقوى صفحة في لوحة المسؤول: الإعدادات. خمسة تبويبات — بنك الأسئلة، الوظائف، الإعلانات، أوزان التقييم، وإدارة المستخدمين.",
    spotlight: { selector: "main", label: "إعدادات المنصّة" }, durationEstimateMs: 15_000 },
  { id: "act6-candidate-detail", act: "Act 6 — Admin",
    narration: "ندخل على ملف سعد كاملاً. سيرته، مقابلة تدريب، ومقابلة تقييم — كلها تحت ملف واحد. هذا التكامل هو جوهر المنصّة.",
    spotlight: { selector: "main", label: "ملف سعد" }, durationEstimateMs: 13_000 },
  { id: "act6-live-proctor", act: "Act 6 — Admin", route: "/admin/proctor",
    narration: "في وقت المقابلات الرسمية، المسؤول يقدر يشاهد الجلسة مباشرةً عبر Live Proctor — أو يشاهد التسجيل لاحقاً.",
    spotlight: { selector: "main", label: "المراقبة المباشرة" }, durationEstimateMs: 12_000 },

  { id: "act6.5-session-swap-hr", act: "Act 6.5 — HR",
    narration: "غير المسؤول التقني، فِرَق الموارد البشرية لها لوحة مخصّصة. لنبدّل إلى حساب HR…",
    action: { kind: "swap-session", role: "hr" }, durationEstimateMs: 7_000 },
  { id: "act6.5-hr-dashboard", act: "Act 6.5 — HR", route: "/dashboard/hr",
    narration: "لوحة الـ HR. مؤشّرات رئيسية: وقت التوظيف، معدّل التحويل، عدد المرشّحين في كل مرحلة.",
    spotlight: { selector: "main", label: "لوحة الـ HR" }, durationEstimateMs: 10_000 },
  { id: "act6.5-pipeline", act: "Act 6.5 — HR", route: "/dashboard/hr/pipeline",
    narration: "خطّ التوظيف بشكل Kanban: تقديم ← فرز ← مقابلة ← عرض ← تعيين. خلّيني أحرّك بطاقة سعد مرحلة للأمام مباشرةً.",
    spotlight: { selector: "main", label: "خطّ التوظيف" }, durationEstimateMs: 13_000 },
  { id: "act6.5-compare", act: "Act 6.5 — HR", route: "/dashboard/hr/compare",
    narration: "ومقارنة المرشّحين جنبًا إلى جنب. سعد مقابل خالد. كل المقاييس: DISC، الدرجات، STAR، radar — في عَرض موحَّد.",
    spotlight: { selector: "main", label: "مقارنة المرشّحين" }, durationEstimateMs: 13_000 },

  { id: "act7-instructor", act: "Act 7 — Instructor", route: "/dashboard/instructor",
    narration: "وأخيرًا، جانب المدرّبين في معهد الإدارة العامة. دفعات (Cohorts)، طلّاب، مهام، وأهم ميزة: تعليقات على لحظات محدّدة من تسجيل المقابلة.",
    spotlight: { selector: "main", label: "لوحة المدرّب" },
    action: { kind: "swap-session", role: "instructor" }, durationEstimateMs: 14_000 },

  { id: "act8-recap", act: "Act 8 — Close", route: "/",
    narration: "وبهذا نختم الجولة. شفنا مسار المرشّح كاملًا، جانب المسؤول، جانب الـ HR، وجانب المدرّب. إذا عندك سؤال أخير، اضغط الميكروفون.",
    spotlight: { selector: "h1", label: "الختام" }, durationEstimateMs: 13_000 },
  { id: "act8-cta", act: "Act 8 — Close", route: "/login?tab=signup",
    narration: "إذا حابب تجرّب بنفسك، عبّي هذا النموذج بإيميلك الحقيقي. راح تبدأ من نفس المكان اللي بدأ منه سعد. شكراً وأهلًا بك في معهد الإدارة العامة.",
    spotlight: { selector: "form", label: "ابدأ مجاناً" }, durationEstimateMs: 14_000 },
];
